rest:
  ssl: true
  host: api7.dspace.org
  port: 443
  nameSpace: /server

################################################
# Enable optional features for demo7.dspace.org
################################################

# Enable anonymous user SSR cache for up to 500 pages.
cache:
  serverSide:
    anonymousCache:
      max: 500

# Enable Item access status badges
item:
  showAccessStatuses: true

# Enable media viewer plugin
mediaViewer:
  image: true
  video: true

# Enable Markdown and MathJax
markdown:
  enabled: true
  mathjax: true

# Enable SRSC vocabulary in search filters
vocabularies:
  - filter: 'subject'
    vocabulary: 'srsc'
    enabled: true